//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trace3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportData()
        {
            this.OrderData = new HashSet<OrderData>();
        }
    
        public string ImportDataID { get; set; }
        public string ProductID { get; set; }
        public string MFD { get; set; }
        public string EXP { get; set; }
        public string Lisence { get; set; }
        public string Declaration { get; set; }
        public int Item { get; set; }
        public string PurchaseNum { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderData> OrderData { get; set; }
    }
}
