//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trace3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderData
    {
        public string ID { get; set; }
        public string OrderID { get; set; }
        public string ShippingDate { get; set; }
        public string Code { get; set; }
        public int Amount { get; set; }
        public string DealerID { get; set; }
        public string ImportDataID { get; set; }
        public double TotalWeight { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual ImportData ImportData { get; set; }
    }
}
