//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trace3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutboundData
    {
        public int ID { get; set; }
        public string OrderID { get; set; }
        public string Owner { get; set; }
        public string DealerID { get; set; }
        public string ShippingData { get; set; }
        public string ProductName { get; set; }
        public string MFD { get; set; }
        public string Lisence { get; set; }
        public string Declaration { get; set; }
        public string EXP { get; set; }
        public string Discription { get; set; }
        public string Amount { get; set; }
        public string Volume { get; set; }
        public string Weight { get; set; }
        public string Code { get; set; }
        public string Driver { get; set; }
        public string CarNum { get; set; }
    }
}
